# 测试配置文件
# @author Charles
# 
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.98.245.102:3306/mianti
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 100.98.245.102
    port: 6379
    timeout: 5000
    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://100.98.245.102:9200
    username: root
    password: 123456