# 测试环境配置
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0:///mianti_test
    username: root
    password: test
  redis:
    database: 0
    host: localhost
    port: 6379
    password: ''
  flyway:
    enabled: false

# 关闭不必要的组件
hotkey:
  app-name: mianti-test
  caffeine-size: 1000
  push-period: 1000
  etcd-server: http://localhost:2379

nacos:
  config:
    enabled: false

sa-token:
  is-log: false

server:
  port: 8102
